[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "历史"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "PPT"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "艺术"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "卡通"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "图片"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "博客"
  url = "posts"
  weight = 5

[[main]]
  parent = "posts"
  name = "剑指offer"
  url = "posts/剑指offer"
