[[main]]
  identifier = "Algorithm_learning"
  url = ""
  name = "算法学习"
  weight = 1

[[main]]
  parent = "Algorithm_learning"
  name = "剑指offer"
  url = "posts/剑指offer目录"


[[main]]
  identifier = "archive"
  name = "历史"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "PPT"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "吃喝玩乐"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "视频"
  url = "gallery/video"

[[main]]
  parent = "gallery"
  name = "图片"
  url = "gallery/photo"