[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "历史"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "PPT"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "艺术"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "视频"
  url = "gallery/video"

[[main]]
  parent = "gallery"
  name = "图片"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "技术分享"
  weight = 5

[[main]]
  identifier = "算法学习"
  parent = "posts"
  name = "算法学习"

  [[main]]
  parent = "算法学习"
  name = "剑指offer"
  url = "posts/剑指offer目录"
