[[main]]
  identifier = "Algorithm_learning"
  url = ""
  name = "算法学习"
  weight = 1

[[main]]
  parent = "Algorithm_learning"
  name = "剑指offer"
  url = "posts/剑指offer目录"

[[main]]
  parent = "Algorithm_learning"
  name = "PPT"
  url = "presentation"

[[main]]
  identifier = "gallery"
  name = "吃喝玩乐"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "视频"
  url = "https://yslinwe.tk/"

[[main]]
  parent = "gallery"
  name = "音乐"
  url = "https://popo-music.vercel.app/"

[[main]]
  parent = "gallery"
  name = "图片"
  url = "gallery/photo"
[[main]]
  identifier = "archive"
  name = "历史墙"
  url = "archive"
  weight = 5

