name: github pages # 名字自取

on:
  push:
    branches:
      - blogSite  # 这里的意思是当 main分支发生push的时候，运行下面的jobs，这里先改为blogSite

jobs:
  deploy: # 任务名自取
    runs-on: ubuntu-18.04	# 在什么环境运行任务
    steps:
      - uses: actions/checkout@v2	# 引用actions/checkout这个action，与所在的github仓库同名
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) 获取submodule主题
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo	# 步骤名自取
        uses: peaceiris/actions-hugo@v2	# hugo官方提供的action，用于在任务环境中获取hugo
        with:
          hugo-version: 'latest'	# 获取最新版本的hugo
          # extended: true

      - name: Build github
        run: hugo --theme=PaperMod --baseUrl="https://yslinwe.github.io" --buildDrafts --minify	# 使用hugo构建静态网页
      # 配置 git
      - name: config git
        run: git config --global user.email "tomdejio@gmail.com"&&git config --global user.name "popoYSL"
      # 使用 git 命令
      - name: check for changes
        run: git status
      - name: git pull
        run: git pull
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "update by github actions"
      - name: push code to master
        run: git push origin master

      - name: Build vercel
        run: hugo --theme=PaperMod --baseUrl="https://popo-blog.vercel.app" --buildDrafts --minify	# 使用hugo构建静态网页
       # 配置 git
      - name: config git
        run: git config --global user.email "tomdejio@gmail.com"&&git config --global user.name "popoYSL"
      # 使用 git 命令
      - name: check for changes
        run: git status
      - name: git pull
        run: git pull
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "update by github actions"
      - name: push code to vercel
        run: git push origin vercel