name: github pages # 名字自取

on:
  push:
    branches:
      - blogSite  # 这里的意思是当 main分支发生push的时候，运行下面的jobs，这里先改为blogSite

jobs:
  deploy: # 任务名自取
    runs-on: ubuntu-18.04	# 在什么环境运行任务
    steps:
      - uses: actions/checkout@v2	# 引用actions/checkout这个action，与所在的github仓库同名
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive) 获取submodule主题
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo	# 步骤名自取
        uses: peaceiris/actions-hugo@v2	# hugo官方提供的action，用于在任务环境中获取hugo
        with:
          hugo-version: 'latest'	# 获取最新版本的hugo
          # extended: true

      - name: Build github
        run: hugo --theme=PaperMod --baseUrl="https://yslinwe.github.io" --buildDrafts --minify	# 使用hugo构建静态网页

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3	# 一个自动发布github pages的action
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }} 该项适用于发布到源码相同repo的情况，不能用于发布到其他repo
          external_repository: yslinwe/yslinwe.github.io	# 发布到哪个repo
          personal_token: ${{ secrets.BLOG }}	# 发布到其他repo需要提供上面生成的personal access token
          publish_dir: ./public	# 注意这里指的是要发布哪个文件夹的内容，而不是指发布到目的仓库的什么位置，因为hugo默认生成静态网页到public文件夹，所以这里发布public文件夹里的内容
          publish_branch: master	# 发布到哪个branch
      
      - name: Build gitee
        run: hugo --theme=PaperMod --baseUrl="https://yslinxx.gitee.io" --buildDrafts --minify	# 使用hugo构建静态网页

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3	# 一个自动发布github pages的action
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }} 该项适用于发布到源码相同repo的情况，不能用于发布到其他repo
          personal_token: ${{ secrets.BLOG }}
          external_repository: yslinwe/yslinwe.github.io	# 发布到哪个repo
          publish_dir: ./public	# 注意这里指的是要发布哪个文件夹的内容，而不是指发布到目的仓库的什么位置，因为hugo默认生成静态网页到public文件夹，所以这里发布public文件夹里的内容
          publish_branch: giteePage	# 发布到哪个branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY 
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:yslinwe/yslinwe.github.io.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:yslinxx/yslinxx.git"
 
 
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: yslinxx
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: yslinxx/yslinxx
          branch: giteePage