name: Sync

on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BLOG }}
        with:
          source-repo: "git@github.com:yslinwe/yslinwe.github.io.git"
          destination-repo: "git@gitee.com:yslinwe/yslinwe.github.io.git"